### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by lzucoffee** [WilliamYang1992/tickets#1]
亲，本人小白一个。下载了这个代码，运行后显示中文乱码怎么解决？O(∩_∩)O谢谢

**Comment by WilliamYang1992** [comment]
@lzucoffee  请问你是在什么环境下运行, 我的是在windows + Python3.5下, 正常没问题,
很抱歉现在才看到评论, 谢谢!

**Comment by lzucoffee** [comment]
没事，没事。我的也是这个环境。后来我换到了Ubuntu里面都没有乱码了
